name: Release binaries

on:
  release:
    types: created

jobs:
  release:
    name: Release Go Binary
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: wangyoucao577/go-release-action@v1.18
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goversion: "https://dl.google.com/go/go1.16.5.linux-amd64.tar.gz"
          goos: linux
          goarch: arm
          pre_command: "export GOARM=6"
          binary_name: "levely"
          ldflags: "-s -w"
          extra_files: LICENSE README.md
